## Append samples of your project ##
resources:
- infrastructure_v1beta1_elementalhost.yaml
- infrastructure_v1beta1_elementalmachine.yaml
- infrastructure_v1beta1_elementalmachinetemplate.yaml
- infrastructure_v1beta1_elementalcluster.yaml
- infrastructure_v1beta1_elementalclustertemplate.yaml
- infrastructure_v1beta1_elementalmachineregistration.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
